num = int(input())
if num == 0:
    print(" * * * ")
    print("*     *")
    print("*     *")
    print("*     *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * * ")
elif num == 1:
    print("       ")
    print("      *")
    print("      *")
    print("      *")
    print("       ")
    print("      *")
    print("      *")
    print("      *")
    print("       ")
elif num == 2:
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print(" * * * ")
    print("*      ")
    print("*      ")
    print("*      ")
    print(" * * * ")
elif num == 3:
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print(" * * * ")
elif num == 4:
    print("       ")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print("       ")
elif num == 5:
    print(" * * * ")
    print("*      ")
    print("*      ")
    print("*      ")
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print(" * * * ")
elif num == 6:
    print(" * * * ")
    print("*      ")
    print("*      ")
    print("*      ")
    print(" * * * ")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * * ")
elif num == 7:
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print("       ")
    print("      *")
    print("      *")
    print("      *")
    print("       ")
elif num == 8:
    print(" * * * ")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * * ")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * * ")
elif num == 9:
    print(" * * * ")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * * ")
    print("      *")
    print("      *")
    print("      *")
    print(" * * * ")